// app/components/Header.vue
<script setup lang="ts">
import { useDisplay } from 'vuetify'

const { smAndUp } = useDisplay()

const getDensity = () => {
  if (smAndUp.value) {
    return 'default'
  }
  return 'compact'
}

const getStyleSnsLinkContainer = () => {
  if (smAndUp.value) {
    return {
      '--min-width-sns-link-container': '4rem',
      '--padding-sns-link-container': '1rem',
    }
  }
  return {
    '--min-width-sns-link-container': '2rem',
    '--padding-sns-link-container': '0.5rem',
  }
}
</script>

<template>
  <v-app-bar color="primary" elevation="0" :density="getDensity()">
    <div class="header-content">
      <div class="header-logo">
        <nuxt-link to="/">
          <v-btn variant="text" color="primary">
            <v-typography
              class="header-title"
              :class="smAndUp ? 'text-h5' : 'text-h6'"
              >{{ siteTitle }}</v-typography
            >
          </v-btn>
        </nuxt-link>
      </div>
      <div class="sns-links">
        <template v-for="(socialInfo, i) in socialInfoList" :key="i">
          <v-btn
            variant="text"
            color="primary"
            class="sns-link-container"
            :style="{ ...getStyleSnsLinkContainer() }"
            :href="socialInfo.url"
            target="_blank"
          >
            <SnsIcon :src="socialInfo.img.path" :alt="socialInfo.img.alt" />
          </v-btn>
        </template>
      </div>
    </div>
  </v-app-bar>
</template>

<style scoped>
.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
}
.header-logo {
  display: flex;
  align-items: center;
}
.sns-link-container {
  --min-width-sns-link-container: 2rem;
  --padding-sns-link-container: 1rem;

  min-width: var(--min-width-sns-link-container);
  padding-inline: var(--padding-sns-link-container);
}
.sns-links {
  display: flex;
  gap: 0.625rem;
  padding-right: 1rem;
}
.header-title {
  color: #000;
  /* font-weight: 700; */
}
</style>

// src/components/header.tsx
import * as React from 'react'
import { Link } from 'gatsby'
import { AppBar, Box, Button, Typography, Link as MuiLink } from '@mui/material'
import TwitterIcon from '@mui/icons-material/Twitter'
import * as utility from '../css/utility.module.css'
import styled from 'styled-components'

type Props = {
  title: string | null | undefined
  twitter: string
  path?: string
}

const StyledBox = styled(Box)`
  display: flex;
  justify-content: space-between;
  align-items: center;
`

export const Header: React.FC<Props> = ({ title, twitter, path }) => {
  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar>
        <StyledBox sx={{ p: { xs: 0, sm: 1 } }}>
          <Link to="/" className={utility.textDecorationNone}>
            <Button sx={{ color: 'primary.contrastText' }}>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                {title}
              </Typography>
            </Button>
          </Link>
          <MuiLink
            target="_blank"
            href={`https://twitter.com/${twitter || ``}`}
          >
            <Button sx={{ color: 'primary.contrastText' }}>
              <TwitterIcon />
            </Button>
          </MuiLink>
        </StyledBox>
      </AppBar>
    </Box>
  )
}
